services:
  photoprism:
    image: photoprism-gpu:latest
    container_name: photoprism
    restart: unless-stopped
    security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
    ports:
    - 2342:2342
    env_file:
    - path: .env
      required: false
    environment:
      PHOTOPRISM_ADMIN_USER: admin
      PHOTOPRISM_ADMIN_PASSWORD: YourSecurePassword
      PHOTOPRISM_AUTH_MODE: password
      PHOTOPRISM_SITE_URL: http://localhost:2342/
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: photoprism
      PHOTOPRISM_DISABLE_WEBDAV: 'false'
      PHOTOPRISM_THUMB_SIZE: 720
      PHOTOPRISM_JPEG_SIZE: 1080
      PHOTOPRISM_WORKERS: 8
      PHOTOPRISM_THUMB_LIBRARY: vips
      PHOTOPRISM_FFMPEG_ENCODER: nvidia
      PHOTOPRISM_DISABLE_TENSORFLOW: 'true'
      PHOTOPRISM_FACE_GPU: 'true'
      PHOTOPRISM_FACE_GPU_PROVIDER: cuda
      OLLAMA_BASE_URL: http://ollama:11434
    volumes:
    - /run/media/jani/J1/Anmol:/photoprism/originals/Anmol
    - /mnt/SATA_1TB/A:/photoprism/originals/SATA_A
    - /run/media/jani/J1/PhotoPrism_Portable/storage:/photoprism/storage
    depends_on:
    - mariadb
    - ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
            - video
            - utility
  mariadb:
    image: mariadb:10.11
    container_name: photoprism_mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - photoprism-db-data:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "photoprism"
      MARIADB_ROOT_PASSWORD: "photoprism"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
    - /run/media/jani/J1/PhotoPrism_Portable/storage/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
  czkawka:
    image: jlesage/czkawka
    container_name: czkawka
    restart: unless-stopped
    ports:
    - 5800:5800
    volumes:
    - /run/media/jani/J1/Anmol:/storage:rw
    - /mnt/SATA_1TB/A:/storage_Z:rw
    - czkawka_config:/config:rw
    environment:
    - USER_ID=1000
    - GROUP_ID=1000
volumes:
  czkawka_config: null
  photoprism-db-data: null
